export const object = {
  data: [
    {
      name: "London",
      local_names: {
        es: "Londres",
        to: "Lonitoni",
        wo: "Londar",
        pl: "Londyn",
        ky: "Лондон",
        ny: "London",
        cu: "Лондонъ",
        tk: "London",
        os: "Лондон",
        si: "ලන්ඩන්",
        gd: "Lunnainn",
        hi: "लंदन",
        mn: "Лондон",
        ab: "Лондон",
        sh: "London",
        he: "לונדון",
        de: "London",
        pa: "ਲੰਡਨ",
        ka: "ლონდონი",
        mk: "Лондон",
        th: "ลอนดอน",
        hr: "London",
        sn: "London",
        na: "London",
        ne: "लन्डन",
        bm: "London",
        ff: "London",
        ig: "London",
        is: "London",
        ht: "Lonn",
        om: "Landan",
        ascii: "London",
        bn: "লন্ডন",
        ro: "Londra",
        uz: "London",
        kv: "Лондон",
        id: "London",
        be: "Лондан",
        yi: "לאנדאן",
        ta: "இலண்டன்",
        am: "ለንደን",
        fy: "Londen",
        fo: "London",
        ml: "ലണ്ടൻ",
        bi: "London",
        sk: "Londýn",
        lb: "London",
        lv: "Londona",
        sq: "Londra",
        ha: "Landan",
        nn: "London",
        zu: "ILondon",
        co: "Londra",
        st: "London",
        sd: "لنڊن",
        ja: "ロンドン",
        ca: "Londres",
        tl: "Londres",
        da: "London",
        so: "London",
        su: "London",
        vo: "London",
        ee: "London",
        vi: "Luân Đôn",
        no: "London",
        sc: "Londra",
        kn: "ಲಂಡನ್",
        mg: "Lôndôna",
        ga: "Londain",
        kk: "Лондон",
        br: "Londrez",
        fr: "Londres",
        rm: "Londra",
        en: "London",
        km: "ឡុងដ៍",
        jv: "London",
        gu: "લંડન",
        ug: "لوندۇن",
        sl: "London",
        fj: "Lodoni",
        ie: "London",
        fi: "Lontoo",
        sr: "Лондон",
        zh: "伦敦",
        bh: "लंदन",
        nv: "Tooh Dineʼé Bikin Haalʼá",
        gl: "Londres",
        el: "Λονδίνο",
        av: "Лондон",
        eo: "Londono",
        wa: "Londe",
        ur: "علاقہ لندن",
        az: "London",
        lt: "Londonas",
        mi: "Rānana",
        hu: "London",
        it: "Londra",
        ln: "Lóndɛlɛ",
        sa: "लन्डन्",
        mr: "लंडन",
        ms: "London",
        fa: "لندن",
        sm: "Lonetona",
        bg: "Лондон",
        oc: "Londres",
        or: "ଲଣ୍ଡନ",
        li: "Londe",
        sv: "London",
        gv: "Lunnin",
        tg: "Лондон",
        hy: "Լոնդոն",
        bo: "ལོན་ཊོན།",
        ar: "لندن",
        tt: "Лондон",
        cy: "Llundain",
        yo: "Lọndọnu",
        tw: "London",
        cv: "Лондон",
        lo: "ລອນດອນ",
        et: "London",
        cs: "Londýn",
        ru: "Лондон",
        ko: "런던",
        uk: "Лондон",
        ia: "London",
        ce: "Лондон",
        qu: "London",
        feature_name: "London",
        eu: "Londres",
        tr: "Londra",
        ps: "لندن",
        nl: "Londen",
        sw: "London",
        gn: "Lóndyre",
        kl: "London",
        ba: "Лондон",
        bs: "London",
        an: "Londres",
        my: "လန်ဒန်မြို့",
        ay: "London",
        se: "London",
        af: "Londen",
        kw: "Loundres",
        io: "London",
        ku: "London",
        te: "లండన్",
        pt: "Londres",
        mt: "Londra",
      },
      lat: 51.5073219,
      lon: -0.1276474,
      country: "GB",
      state: "England",
    },
    {
      name: "City of London",
      local_names: {
        pt: "Cidade de Londres",
        lt: "Londono Sitis",
        uk: "Лондонське Сіті",
        zh: "倫敦市",
        ru: "Сити",
        ur: "لندن شہر",
        he: "הסיטי של לונדון",
        en: "City of London",
        fr: "Cité de Londres",
        hi: "सिटी ऑफ़ लंदन",
        ko: "시티 오브 런던",
        es: "City de Londres",
      },
      lat: 51.5156177,
      lon: -0.0919983,
      country: "GB",
      state: "England",
    },
    {
      name: "London",
      local_names: {
        lv: "Landona",
        iu: "ᓚᓐᑕᓐ",
        yi: "לאנדאן",
        fr: "London",
        cr: "ᓬᐊᐣᑕᐣ",
        lt: "Londonas",
        hy: "Լոնտոն",
        ka: "ლონდონი",
        be: "Лондан",
        he: "לונדון",
        ar: "لندن",
        ru: "Лондон",
        th: "ลอนดอน",
        el: "Λόντον",
        oj: "Baketigweyaang",
        ug: "لوندۇن",
        fa: "لندن",
        en: "London",
        bn: "লন্ডন",
        ko: "런던",
        ga: "Londain",
        ja: "ロンドン",
      },
      lat: 42.9832406,
      lon: -81.243372,
      country: "CA",
      state: "Ontario",
    },
    {
      name: "Chelsea",
      local_names: {
        af: "Chelsea, Londen",
        el: "Τσέλσι",
        he: "צ'לסי",
        it: "Chelsea",
        hu: "Chelsea",
        eu: "Chelsea",
        ja: "チェルシー",
        ur: "چیلسی، لندن",
        vi: "Chelsea, Luân Đôn",
        tr: "Chelsea, Londra",
        uk: "Челсі",
        ko: "첼시",
        es: "Chelsea",
        sk: "Chelsea",
        no: "Chelsea",
        zh: "車路士",
        sh: "Chelsea, London",
        pt: "Chelsea",
        fa: "چلسی",
        sv: "Chelsea, London",
        pl: "Chelsea",
        ar: "تشيلسي",
        et: "Chelsea",
        fr: "Chelsea",
        da: "Chelsea",
        en: "Chelsea",
        ru: "Челси",
        id: "Chelsea, London",
        ga: "Chelsea",
        de: "Chelsea",
        nl: "Chelsea",
        az: "Çelsi",
        hi: "चेल्सी, लंदन",
      },
      lat: 51.4875167,
      lon: -0.1687007,
      country: "GB",
      state: "England",
    },
    {
      name: "London",
      lat: 37.1289771,
      lon: -84.0832646,
      country: "US",
      state: "Kentucky",
    },
  ],
  status: 200,
  statusText: "OK",
  headers: {
    "content-length": "4401",
    "content-type": "application/json; charset=utf-8",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    adapter: ["xhr", "http"],
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: "application/json, text/plain, */*",
    },
    method: "get",
    url: "https://api.openweathermap.org/geo/1.0/direct?q=London&limit=5&appid=7964beee62be8a7b951575f53846b3f0",
  },
  request: {},
};
